---
- name: Deploy Terraform
  hosts: localhost
  remote_user: root

  tasks:
    - name: Basic deploy of a service
      community.general.terraform:
        project_path: './'
        state: present