name: testing workflow

env:
  TERRAFORM_VERSION: 1.9.6
  AWS_REGION: eu-west-1
  AWS_S3_BUCKET: ${{ vars.AWS_S3_BUCKET }}
  ROLE_TO_ASSUME: ${{ secrets.ROLE_TO_ASSUME }}
  ROLE_SESSION_NAME: Github_AWS

on:
  push:
    branches:
      - test

permissions:
  id-token: write   # This is required for requesting the JWT
  contents: read    # This is required for actions/checkout

jobs:
  get-file:
    name: Get S3 File
    runs-on: ubuntu-latest
    steps:
    - name: Git clone the repository
      uses: actions/checkout@v3
        
    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v2
      with:
        role-to-assume: ${{ env.ROLE_TO_ASSUME }}
        aws-region: ${{ env.AWS_REGION }}

    - uses: keithweaver/aws-s3-github-action@v1.0.0
      name: Copy Folder
      with:
        command: cp
        source: s3://gh-test-lfs/9.3.3.0-IBM-MQC-Redist-LinuxX64.zip
        destination: ./9.3.3.0-IBM-MQC-Redist-LinuxX64.zip
        aws_region: ${{ env.AWS_REGION }}

    - run: ls -al
